Review 2
KanVull/clothes-app-rails pull request #3
Opened 2024-03-21 12:21 UTC by KanVull

Added show product page

2024-03-21 12:21 UTC, KanVull commented
There will be commits with letter_opener gem

2024-03-21 12:54 UTC, igor-alexandrov requested changes

2024-03-21 12:54 UTC, igor-alexandrov commented on app/controllers/products_controller.rb
> +    @product = Product.find_by!(id: params[:id])
Lets replace this with `find`.

2024-03-21 13:09 UTC, KanVull commented
This order link is not secure. It would probably be nice to create a unique id (like: kasdjf3434lkfjkld) for order and give the access to order by link our_site.com/orders/kasdjf3434lkfjkld

2024-03-22 14:13 UTC, KanVull commented
Added UUID to order, returned id, fixed mailer, fixed variable scope set_cart method to private.

2024-03-27 13:00 UTC, merged